"""
purecoder/anchors.py

Contract examples -> executable assertions, generated by code rather than by a
model. This is what changes the trust model: the assertions encoding behaviour
the spec states explicitly are no longer the model's opinion about its own
work.

Kept apart from contract.py deliberately. That module handles a contract's
lifecycle; this one emits Python source from it.
"""

import ast
import builtins
import re

# `out` may name an exception instead of a value: "raises ValueError".
RAISES = re.compile(r"^raises\s+([A-Za-z_][A-Za-z0-9_]*)$")


def _is_builtin_exception(name):
    obj = getattr(builtins, name, None)
    return isinstance(obj, type) and issubclass(obj, BaseException)


def anchor_tests(contract):
    """Contract examples -> assertion source, generated by code not by a model.

    Returns (source, dropped). Every block is parsed before it is accepted, so
    one malformed example cannot poison the suite -- it is dropped with a
    reason instead, and the caller reports it.
    """
    name = contract["name"]
    blocks, dropped = [], []

    for i, ex in enumerate(contract.get("examples", []), 1):
        args = ex.get("in", "").strip()
        expected = ex.get("out", "").strip()

        raises = RAISES.match(expected)
        if raises:
            exc = raises.group(1)
            # An anchor runs before the implementation exists, so it can only
            # name an exception that already does. Custom classes reach the
            # test designer through the rendered contract instead.
            if not _is_builtin_exception(exc):
                dropped.append(f"example {i}: {exc} is not a built-in exception")
                continue
            block = (f"try:\n"
                     f"    {name}({args})\n"
                     f"    assert False\n"
                     f"except {exc}:\n"
                     f"    pass")
        else:
            block = f"assert {name}({args}) == {expected}"

        try:
            ast.parse(block)
        except SyntaxError:
            dropped.append(f"example {i}: does not parse -- "
                           f"in={args!r} out={expected!r}")
            continue
        blocks.append(block)

    return "\n".join(blocks), dropped
