"""
purecoder/anchors.py

Contract examples -> executable assertions, generated by code rather than by a
model. This is what changes the trust model: the assertions encoding behaviour
the spec states explicitly are no longer the model's opinion about its own
work.

Kept apart from contract.py deliberately. That module handles a contract's
lifecycle; this one emits Python source from it.
"""

import ast
import builtins
import re

# `out` may name an exception instead of a value: "raises ValueError".
RAISES = re.compile(r"^raises\s+([A-Za-z_][A-Za-z0-9_]*)$")


def _is_builtin_exception(name):
    obj = getattr(builtins, name, None)
    return isinstance(obj, type) and issubclass(obj, BaseException)


def _expression_error(text, side, i):
    """Reject anything that is not ONE Python expression.

    Contract text is interpolated into an assertion, so a fragment that
    happens to parse in context can silently rewrite the assertion around it:
    `out` of `3, 1` turns `assert f(10, 3) == 3, 1` into an assert-with-message
    that only checks `== 3`, and an `in` of `1) or True; f(2` splits the block
    into two statements. Both parse, so parsing the finished block is not
    enough -- each side has to stand alone first.
    """
    try:
        ast.parse(text, mode="eval")
    except SyntaxError:
        return (f"example {i}: {side!r} is not a single Python expression -- "
                f"{text!r}")
    return ""


def count_anchors(source: str) -> int:
    """How many anchor blocks `source` holds.

    One definition of "an anchor", shared by the assertion floor in execute.py
    and the CLI's report. An equality anchor is a single `assert` line; a
    raises anchor is a `try:` block -- its nested `assert False` is indented,
    so it is not counted a second time.
    """
    return sum(1 for line in source.splitlines()
               if line.startswith(("assert", "try:")))


def anchor_tests(contract):
    """Contract examples -> assertion source, generated by code not by a model.

    Returns (source, dropped). Both sides of an example are validated as
    standalone expressions before interpolation and the finished block must be
    exactly one statement, so one malformed example cannot poison the suite --
    it is dropped with a reason instead, and the caller reports it.
    """
    name = contract["name"]
    blocks, dropped = [], []

    for i, ex in enumerate(contract.get("examples", []), 1):
        args = ex.get("in", "").strip()
        expected = ex.get("out", "").strip()

        # An empty argument list is a legitimate zero-argument call; that is
        # the only `in` allowed to skip the expression check.
        if args:
            err = _expression_error(args, "in", i)
            if err:
                dropped.append(err)
                continue

        raises = RAISES.match(expected)
        if raises:
            exc = raises.group(1)
            # An anchor runs before the implementation exists, so it can only
            # name an exception that already does. Custom classes reach the
            # test designer through the rendered contract instead.
            if not _is_builtin_exception(exc):
                dropped.append(f"example {i}: {exc} is not a built-in exception")
                continue
            # try/except/else, never `assert False` inside the try: when exc
            # is AssertionError the except would catch our own marker and the
            # anchor would pass on a function that raised nothing.
            block = (f"try:\n"
                     f"    {name}({args})\n"
                     f"except {exc}:\n"
                     f"    pass\n"
                     f"else:\n"
                     f"    assert False")
        else:
            if not expected:
                dropped.append(f"example {i}: 'out' is empty -- nothing "
                               "to assert")
                continue
            err = _expression_error(expected, "out", i)
            if err:
                dropped.append(err)
                continue
            # Parenthesised: an unbracketed `expected` would bind to whatever
            # follows the `==` rather than to the comparison.
            block = f"assert {name}({args}) == ({expected})"

        try:
            tree = ast.parse(block)
        except SyntaxError:
            dropped.append(f"example {i}: does not parse -- "
                           f"in={args!r} out={expected!r}")
            continue
        # One example, one statement. Anything else means the interpolated
        # text brought structure of its own.
        if len(tree.body) != 1:
            dropped.append(f"example {i}: emits {len(tree.body)} statements, "
                           f"not one -- in={args!r} out={expected!r}")
            continue
        blocks.append(block)

    return "\n".join(blocks), dropped
