"""
purecoder/contract.py

The spec contract: a structured, grammar-constrained statement of what a
function must do, derived from prose before any code exists.

It exists because of the one failure the other layers cannot see. The writer
and the code-blind test designer both read the same prose; when they misread it
the same way, the tests agree with the bug and the loop reports success. A
contract makes that shared interpretation a single artifact you can read, and
turns the behaviour the spec states explicitly into assertions generated by
code rather than by a model.

It does not make the contract correct. It makes it visible. Those are
different claims and the docs keep them apart.
"""

import json
import keyword

REQUIRED_KEYS = ("name", "summary", "params", "returns", "raises", "examples")


def _identifier_error(value, what):
    """Shared guard: contracts name things that must be valid Python names."""
    if not isinstance(value, str) or not value.isidentifier():
        return f"{what} is not a valid identifier: {value!r}"
    if keyword.iskeyword(value):
        return f"{what} is a Python keyword: {value!r}"
    return ""


def validate_contract(obj):
    """Semantic guards the grammar cannot express. Returns (ok, error).

    The grammar guarantees the SHAPE of the JSON. It cannot know that `name`
    must be a callable identifier or that an empty examples list makes the
    whole contract useless -- same division of labour as the Makefile
    validator, where `make -n` proves parsing and the guards prove sense.
    """
    if not isinstance(obj, dict):
        return False, f"contract is not a JSON object: {type(obj).__name__}"

    for key in REQUIRED_KEYS:
        if key not in obj:
            return False, f"missing required key {key!r}"

    err = _identifier_error(obj["name"], "name")
    if err:
        return False, err

    if not isinstance(obj["params"], list):
        return False, "params is not a list"
    for i, param in enumerate(obj["params"], 1):
        if not isinstance(param, dict) or "name" not in param or "type" not in param:
            return False, f"param {i}: needs both 'name' and 'type'"
        err = _identifier_error(param["name"], f"param {i} name")
        if err:
            return False, err

    if not isinstance(obj["raises"], list):
        return False, "raises is not a list"
    for i, item in enumerate(obj["raises"], 1):
        if not isinstance(item, dict) or "exc" not in item or "when" not in item:
            return False, f"raises {i}: needs both 'exc' and 'when'"
        err = _identifier_error(item["exc"], f"raises {i} exception name")
        if err:
            return False, err

    if not isinstance(obj["examples"], list) or not obj["examples"]:
        return False, "examples is empty -- a contract with no example is untestable"
    for i, ex in enumerate(obj["examples"], 1):
        if not isinstance(ex, dict):
            return False, f"example {i}: not an object"
        for side in ("in", "out"):
            if side not in ex or not isinstance(ex[side], str):
                return False, f"example {i}: missing string {side!r}"

    return True, ""


CONTRACT_SYSTEM = (
    "You output only a JSON contract describing the function the user asks "
    "for. No prose, no explanation, no code fences. Capture ONLY what the "
    "description states -- do not invent requirements. Every error case the "
    "description mentions must appear in 'raises'. Give at least two "
    "'examples': 'in' is the argument list as Python source (empty string for "
    "no arguments), 'out' is either a Python expression for the expected "
    "return value or the exact form 'raises ExceptionName'."
)


def render_contract(contract):
    """The 'what I assumed' block. This is the whole point of the layer: a
    wrong interpretation is worth far more when it is visible than when it is
    buried in generated tests."""
    lines = [f"Contract for `{contract['name']}`: {contract['summary']}"]

    params = contract.get("params") or []
    if params:
        joined = ", ".join(f"{p['name']}: {p['type']}" for p in params)
        lines.append(f"  params  : {joined}")
    else:
        lines.append("  params  : (none)")

    lines.append(f"  returns : {contract['returns']}")

    raises = contract.get("raises") or []
    if raises:
        for item in raises:
            lines.append(f"  raises  : {item['exc']} when {item['when']}")
    else:
        lines.append("  raises  : (nothing)")

    for ex in contract.get("examples") or []:
        lines.append(f"  example : {contract['name']}({ex['in']}) -> {ex['out']}")

    return "\n".join(lines)


def derive_contract(pc, description, max_retries=3, verbose=True):
    """Prose -> validated contract. Returns (contract, error); contract is
    None on failure so the caller can fall back rather than abort.

    Same write -> validate -> fix shape as the config loop, with JSON decoding
    counted as a validation failure: a truncated object is invalid JSON, so
    truncation is retried by the same path.
    """
    task, error = description, ""

    for attempt in range(1, max_retries + 1):
        try:
            res = pc.complete(system=CONTRACT_SYSTEM, user=task,
                              grammar="contract", n_predict=512)
        except RuntimeError as e:
            # A dead server must not kill the run -- the caller falls back.
            return None, str(e)

        try:
            obj = json.loads(res["text"])
            ok, error = validate_contract(obj)
        except json.JSONDecodeError as e:
            ok, error = False, f"not valid JSON: {e}"

        if ok:
            if verbose:
                print(f"[contract] derived on attempt {attempt}")
            return obj, ""

        if verbose:
            print(f"[contract] attempt {attempt} rejected: {error} -> retrying")
        task = (f"{description}\n\n"
                f"Your previous contract was rejected: {error}\n"
                f"Output only the corrected JSON contract, nothing else.")

    return None, error
