"""
purecoder/contract.py

The spec contract: a structured, grammar-constrained statement of what a
function must do, derived from prose before any code exists.

It exists because of the one failure the other layers cannot see. The writer
and the code-blind test designer both read the same prose; when they misread it
the same way, the tests agree with the bug and the loop reports success. A
contract makes that shared interpretation a single artifact you can read, and
turns the behaviour the spec states explicitly into assertions generated by
code rather than by a model.

It does not make the contract correct. It makes it visible. Those are
different claims and the docs keep them apart.
"""

import keyword

REQUIRED_KEYS = ("name", "summary", "params", "returns", "raises", "examples")


def _identifier_error(value, what):
    """Shared guard: contracts name things that must be valid Python names."""
    if not isinstance(value, str) or not value.isidentifier():
        return f"{what} is not a valid identifier: {value!r}"
    if keyword.iskeyword(value):
        return f"{what} is a Python keyword: {value!r}"
    return ""


def validate_contract(obj):
    """Semantic guards the grammar cannot express. Returns (ok, error).

    The grammar guarantees the SHAPE of the JSON. It cannot know that `name`
    must be a callable identifier or that an empty examples list makes the
    whole contract useless -- same division of labour as the Makefile
    validator, where `make -n` proves parsing and the guards prove sense.
    """
    if not isinstance(obj, dict):
        return False, f"contract is not a JSON object: {type(obj).__name__}"

    for key in REQUIRED_KEYS:
        if key not in obj:
            return False, f"missing required key {key!r}"

    err = _identifier_error(obj["name"], "name")
    if err:
        return False, err

    if not isinstance(obj["params"], list):
        return False, "params is not a list"
    for i, param in enumerate(obj["params"], 1):
        if not isinstance(param, dict) or "name" not in param or "type" not in param:
            return False, f"param {i}: needs both 'name' and 'type'"
        err = _identifier_error(param["name"], f"param {i} name")
        if err:
            return False, err

    if not isinstance(obj["raises"], list):
        return False, "raises is not a list"
    for i, item in enumerate(obj["raises"], 1):
        if not isinstance(item, dict) or "exc" not in item or "when" not in item:
            return False, f"raises {i}: needs both 'exc' and 'when'"
        err = _identifier_error(item["exc"], f"raises {i} exception name")
        if err:
            return False, err

    if not isinstance(obj["examples"], list) or not obj["examples"]:
        return False, "examples is empty -- a contract with no example is untestable"
    for i, ex in enumerate(obj["examples"], 1):
        if not isinstance(ex, dict):
            return False, f"example {i}: not an object"
        for side in ("in", "out"):
            if side not in ex or not isinstance(ex[side], str):
                return False, f"example {i}: missing string {side!r}"

    return True, ""
